//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTBaseViewController.h"

#import "TTTAttributedLabelDelegate.h"

@class MMContactRecommendInfo, MMContactRecommendView, MMContactUploadView, NSString, RACCommand, TTTAttributedLabel, UIButton, UILabel, UIScrollView;

@interface AddressBookUploadViewController : NTBaseViewController <TTTAttributedLabelDelegate>
{
    _Bool _isUpdateReady;
    _Bool _isUpdateUploading;
    _Bool _isAppear;
    NSString *_whoInviteMe;
    MMContactRecommendInfo *_recommendInfo;
    long long _clickStatus;
    UIScrollView *_contentScrollView;
    MMContactRecommendView *_recommendView;
    MMContactUploadView *_uploadView;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    UIButton *_okButton;
    TTTAttributedLabel *_hintLabel;
    RACCommand *_cancelCommand;
}

+ (void)pingback:(long long)arg1;
@property(nonatomic) _Bool isAppear; // @synthesize isAppear=_isAppear;
@property(retain, nonatomic) RACCommand *cancelCommand; // @synthesize cancelCommand=_cancelCommand;
@property(retain, nonatomic) TTTAttributedLabel *hintLabel; // @synthesize hintLabel=_hintLabel;
@property(retain, nonatomic) UIButton *okButton; // @synthesize okButton=_okButton;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak MMContactUploadView *uploadView; // @synthesize uploadView=_uploadView;
@property(nonatomic) __weak MMContactRecommendView *recommendView; // @synthesize recommendView=_recommendView;
@property(nonatomic) __weak UIScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(nonatomic) _Bool isUpdateUploading; // @synthesize isUpdateUploading=_isUpdateUploading;
@property(nonatomic) _Bool isUpdateReady; // @synthesize isUpdateReady=_isUpdateReady;
@property(nonatomic) long long clickStatus; // @synthesize clickStatus=_clickStatus;
@property(retain, nonatomic) MMContactRecommendInfo *recommendInfo; // @synthesize recommendInfo=_recommendInfo;
@property(retain, nonatomic) NSString *whoInviteMe; // @synthesize whoInviteMe=_whoInviteMe;
- (void).cxx_destruct;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (void)pingback:(long long)arg1;
- (void)pingbackClickRefuse;
- (void)pingbackClickAllow;
- (void)pingbackClickConfirm;
- (void)refreshHintLabel2:(id)arg1;
- (void)refreshHintLabel:(id)arg1;
- (void)handleAddressBookCheckNotification:(id)arg1;
- (void)uploadResult:(long long)arg1 errorMsg:(id)arg2;
- (void)function:(id)arg1;
- (void)stopAnimating;
- (void)startAnimating;
- (void)setupRAC;
- (void)setupViews;
- (void)viewDidLoad;
- (long long)defaultNaviBarStyle;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

