//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface MMAddressBookManager : NSObject
{
    NSArray *localMobiles;
    _Bool _isAllowCheckOnlineContacts;
    _Bool _hasShowTips;
    long long _state;
    unsigned long long _increaseCount;
    NSString *_updateAdressBookText;
    unsigned long long _showUploadContactTipsTag;
    double _lastAlertTimestamp;
    double _lastUploadTimestampStored;
    double _lastUploadTimestamp;
}

+ (id)readAddressBookFromRecord:(void *)arg1;
+ (id)makeOnlineFormatFromMobile:(id)arg1;
+ (id)sharedManager;
@property(nonatomic) double lastUploadTimestamp; // @synthesize lastUploadTimestamp=_lastUploadTimestamp;
@property(nonatomic) double lastUploadTimestampStored; // @synthesize lastUploadTimestampStored=_lastUploadTimestampStored;
@property(nonatomic) double lastAlertTimestamp; // @synthesize lastAlertTimestamp=_lastAlertTimestamp;
@property(nonatomic) _Bool hasShowTips; // @synthesize hasShowTips=_hasShowTips;
@property(nonatomic) _Bool isAllowCheckOnlineContacts; // @synthesize isAllowCheckOnlineContacts=_isAllowCheckOnlineContacts;
@property(nonatomic) unsigned long long showUploadContactTipsTag; // @synthesize showUploadContactTipsTag=_showUploadContactTipsTag;
@property(retain, nonatomic) NSString *updateAdressBookText; // @synthesize updateAdressBookText=_updateAdressBookText;
@property(nonatomic) unsigned long long increaseCount; // @synthesize increaseCount=_increaseCount;
@property(nonatomic) long long state; // @synthesize state=_state;
- (void).cxx_destruct;
- (void)updateLastUploadTimestamp:(double)arg1;
- (void)updateAddressBook:(id)arg1;
- (void)autoUpdateAddressBook;
- (void)checkAddressBook:(id)arg1;
- (void)cancelCheckAddressBook;
- (_Bool)isPostNotificationForCheckFinish;
- (void)mergeContacts:(id)arg1;
- (void)loadLocalAddressBook;
- (void)refresh;
- (id)init;

@end

