//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "UIApplicationDelegate.h"
#import "UITabBarControllerDelegate.h"
#import "WXApiDelegate.h"

@class NSObject<OS_dispatch_semaphore>, NSString, NTGlobal, NTMessageDaemon, NTRootTabViewController, Reachability, UIStoryboard, UIWindow;

@interface NTAppDelegate : UIResponder <UIApplicationDelegate, WXApiDelegate, UITabBarControllerDelegate>
{
    NTGlobal *global;
    NTMessageDaemon *messageDaemon;
    _Bool _launchActived;
    _Bool _inActiveMode;
    _Bool _initPushEnabled;
    _Bool _didEnterForeground;
    _Bool _isWaitingForSplash;
    _Bool _isSplashWillShow;
    _Bool _isSplashGuideWillShow;
    _Bool _hasSplash;
    _Bool _hasSplashGuide;
    _Bool _isJumpIn;
    UIWindow *_window;
    NTRootTabViewController *_rootViewController;
    UIStoryboard *_myStoryboard;
    Reachability *_reachability;
    NSObject<OS_dispatch_semaphore> *_splashSemaphore;
    long long _beforeWaitIv;
    long long _afterWaitIv;
}

+ (_Bool)sendWeixinVideo:(id)arg1 content:(id)arg2 thumbImg:(id)arg3 shareTarget:(long long)arg4 shareUrl:(id)arg5 callback:(CDUnknownBlockType)arg6;
+ (_Bool)sendWeixinWebpage:(id)arg1 content:(id)arg2 thumbImg:(id)arg3 shareTarget:(long long)arg4 shareUrl:(id)arg5;
+ (_Bool)sendWeixinWebpage:(id)arg1 content:(id)arg2 thumbImg:(id)arg3 shareTarget:(long long)arg4 shareUrl:(id)arg5 callback:(CDUnknownBlockType)arg6;
+ (_Bool)sendWeixinImagePng:(id)arg1 shareTarget:(long long)arg2 callback:(CDUnknownBlockType)arg3;
+ (_Bool)sendWeixinImage:(id)arg1 content:(id)arg2 thumbImg:(id)arg3 shareTarget:(long long)arg4 callback:(CDUnknownBlockType)arg5;
+ (void)setRootMobileVerifyController;
+ (void)setRootUploadContactsController;
+ (void)setRootLoginController;
+ (void)setRootTabControllerBelow:(id)arg1;
+ (void)setRootTabController;
@property(nonatomic) long long afterWaitIv; // @synthesize afterWaitIv=_afterWaitIv;
@property(nonatomic) long long beforeWaitIv; // @synthesize beforeWaitIv=_beforeWaitIv;
@property _Bool isJumpIn; // @synthesize isJumpIn=_isJumpIn;
@property _Bool hasSplashGuide; // @synthesize hasSplashGuide=_hasSplashGuide;
@property _Bool hasSplash; // @synthesize hasSplash=_hasSplash;
@property _Bool isSplashGuideWillShow; // @synthesize isSplashGuideWillShow=_isSplashGuideWillShow;
@property _Bool isSplashWillShow; // @synthesize isSplashWillShow=_isSplashWillShow;
@property _Bool isWaitingForSplash; // @synthesize isWaitingForSplash=_isWaitingForSplash;
@property(retain) NSObject<OS_dispatch_semaphore> *splashSemaphore; // @synthesize splashSemaphore=_splashSemaphore;
@property(retain, nonatomic) Reachability *reachability; // @synthesize reachability=_reachability;
@property(retain, nonatomic) UIStoryboard *myStoryboard; // @synthesize myStoryboard=_myStoryboard;
@property(retain, nonatomic) NTRootTabViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)remoteControlReceivedWithEvent:(id)arg1;
- (_Bool)canBecomeFirstResponder;
- (void)application:(id)arg1 didRegisterUserNotificationSettings:(id)arg2;
- (void)application:(id)arg1 performFetchWithCompletionHandler:(CDUnknownBlockType)arg2;
- (void)hideSplash:(id)arg1;
- (void)showAdpingBack:(long long)arg1 condidPara:(long long)arg2;
- (void)asyncRequestGlobalConfig;
- (_Bool)asyncCheckSpashGuideResult;
- (void)showGuide:(id)arg1;
- (_Bool)asyncCheckImageResult:(id)arg1;
- (_Bool)asycnCheckVideoResult:(id)arg1;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (void)networkStatusNotification:(id)arg1;
- (void)checkUpdate;
- (void)onResp:(id)arg1;
- (void)onReq:(id)arg1;
- (_Bool)application:(id)arg1 handleOpenURL:(id)arg2;
- (void)message:(id)arg1;
- (void)application:(id)arg1 handleActionWithIdentifier:(id)arg2 forRemoteNotification:(id)arg3 withResponseInfo:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)application:(id)arg1 handleActionWithIdentifier:(id)arg2 forRemoteNotification:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)application:(id)arg1 handleActionWithIdentifier:(id)arg2 forLocalNotification:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (_Bool)tabBarController:(id)arg1 shouldSelectViewController:(id)arg2;
- (void)loadWebView:(id)arg1;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)installCrash;
- (void)syncUI;
- (void)syncData;
- (void)asyncSetting;
- (void)syncSetting;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

