//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTTableFormViewController.h"

#import "TTTAttributedLabelDelegate.h"

@class MMMobile, MMMobileCountryPicker, NSMutableArray, NSString, TTTAttributedLabel, UIButton, UILabel, UILongPressGestureRecognizer, UITextField, UIView;

@interface NTPhoneLoginViewController : NTTableFormViewController <TTTAttributedLabelDelegate>
{
    NSMutableArray *cells;
    UITextField *phoneInput;
    UITextField *passwdInput;
    UIButton *loginBtn;
    UIButton *forgetbtn;
    UILongPressGestureRecognizer *longPressGR;
    MMMobileCountryPicker *mobileCountryPicker;
    NSString *_loginPhone;
    UILabel *_countryLabel;
    UIButton *_ccodeButton;
    MMMobile *_mobileModel;
    TTTAttributedLabel *_hintLabel;
    UIView *_footer;
}

@property(retain, nonatomic) UIView *footer; // @synthesize footer=_footer;
@property(retain, nonatomic) TTTAttributedLabel *hintLabel; // @synthesize hintLabel=_hintLabel;
@property(retain, nonatomic) MMMobile *mobileModel; // @synthesize mobileModel=_mobileModel;
@property(retain, nonatomic) UIButton *ccodeButton; // @synthesize ccodeButton=_ccodeButton;
@property(retain, nonatomic) UILabel *countryLabel; // @synthesize countryLabel=_countryLabel;
@property(retain, nonatomic) NSString *loginPhone; // @synthesize loginPhone=_loginPhone;
- (void).cxx_destruct;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (id)loginName;
- (void)textKeyboardHide;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)countryClicked;
- (void)forgotClick:(id)arg1;
- (void)loginClick:(id)arg1;
- (void)handleLongPress:(id)arg1;
- (void)handleLoginModel:(id)arg1;
- (void)refreshHintLabel;
- (void)setupHintLabel;
- (void)layoutFooter;
- (void)viewDidLoad;
- (long long)tableViewStyle;
- (id)newInputCell:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

